version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - n 22
      
  build:
    commands:
      - npm ci && npm run build
      - aws s3 rm s3://$SITE_BUCKET/ --recursive && aws s3 cp bin s3://$SITE_BUCKET/ --recursive
      - chmod +x invalidate.sh && ./invalidate.sh
