name: Dependabot Auto-Build and Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot:
    # Only run on Dependabot PRs
    if: ${{ github.actor == 'dependabot[bot]' || contains(github.event.pull_request.labels.*.name, 'dependabot') }}
    runs-on: ubuntu-latest
    permissions:
      # Required for auto-merge
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        id: build
        run: npm run build:ci

      - name: Lint
        id: lint
        run: npm run lint
      
      - name: Enable auto-merge
        if: success()
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
