name: Dependabot Auto-Review

on:
  workflow_run:
    workflows: ["Dependabot Auto-Build and Merge"]
    types:
      - completed

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      pull-requests: write
      
    steps:
      - name: Find and approve Dependabot PRs
        run: |
          # Get the PR number from the workflow that triggered this one
          PR_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} | jq -r '.pull_requests[0].number')
          
          if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
            # Check if PR is from Dependabot
            ACTOR=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER | jq -r '.user.login')
            
            if [ "$ACTOR" = "dependabot[bot]" ]; then
              echo "Approving Dependabot PR #$PR_NUMBER"
              gh pr review $PR_NUMBER --approve
            else
              echo "PR #$PR_NUMBER is not from Dependabot, skipping approval"
            fi
          else
            echo "No associated PR found for this workflow run"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}